name: {{cookiecutter.project_name}}
dependencies:
{% if cookiecutter.python_interpreter != 'python3' %}
- python=2.7
{% else %}
- python=3.6
{% endif %}
- NumPy>=1.6.1
- SciPy>=0.9
- scikit-learn>=0.18
- pytest
- jupyter
- matplotlib
- seaborn
- pandas
- statsmodels
- dill
- click
- Sphinx
- coverage
- flake8
- pip
- pip:
  - pytest-runner
  - awscli
  - python-dotenv>=0.5.1
  - pandas_profiling
  - -rgithubrequirements.txt
# local package
  - -e .
{% if cookiecutter.python_interpreter != 'python3' %}
# backwards compatibility
  - pathlib2
{% endif %}
