name: {{cookiecutter.project_name}}
dependencies:
#- python=2.7
- NumPy>=1.6.1
- SciPy>=0.9
- pytest
- jupyter
- matplotlib
- pandas
- statsmodels
- click
- Sphinx
- coverage
- flake8
- pip
- pip:
  - pytest-runner
  - awscli
  - python-dotenv>=0.5.1
